spring:
  application:
    name: department-service-ms
  profiles:
    active: "dev"

names:
  message: "Name message default"
  details:
    name: Abc d
    email: abc@gmail.com
  phone:
    - 123456
    - 234566
