spring:
  config:
    activate:
      on-profile: 'prod'

names:
  message: "Name message production-git-refresh drpt-dept-auto-1"
  details:
    name: production d3
    email: production3@gmail.com
  phone:
    - 123456-prod
    - 234566-prod
