spring:
  application:
    name: "empservice"
  profiles:
    active: "dev"

names:
  message: "Name message emp change one"
  details:
    name: Abc d
    email: abc@gmail.com
  phone:
    - 123456
    - 234566
